email = input('Hãy nhập email của bạn: ')
password = input ('Hãy nhập mật khẩu của bạn: ')
print (f'Tài khoản của bạn là: {email} - {password}')
print ()
chieu_dai = int (input ('Hãy nhập chiều dài của hình chữ nhật: '))
chieu_rong = int (input ('Hãy nhập chiều rộng của hình chữ nhật: '))
print ('Chu vi của hình chữ nhật đó là: ', (chieu_dai + chieu_rong) * 2)
print ()
canh = int (input ('Hãy nhập cạnh hình vuông: '))
print ('Diện tích của hình vuông đó là: ', canh * canh)